// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ImageUrl             string   `protobuf:"bytes,4,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterUserRequest) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type RegisterUserResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type LoginUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ImageUrl             string   `protobuf:"bytes,4,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Result               string   `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginUserResponse) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *LoginUserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginUserResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type PostRequest struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl             string   `protobuf:"bytes,2,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Option               string   `protobuf:"bytes,4,opt,name=option,proto3" json:"option,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRequest) Reset()         { *m = PostRequest{} }
func (m *PostRequest) String() string { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()    {}
func (*PostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *PostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequest.Unmarshal(m, b)
}
func (m *PostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequest.Marshal(b, m, deterministic)
}
func (m *PostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequest.Merge(m, src)
}
func (m *PostRequest) XXX_Size() int {
	return xxx_messageInfo_PostRequest.Size(m)
}
func (m *PostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequest proto.InternalMessageInfo

func (m *PostRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PostRequest) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *PostRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PostRequest) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *PostRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type PostResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type CommentRequest struct {
	Comment              string   `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Postid               uint32   `protobuf:"varint,4,opt,name=postid,proto3" json:"postid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentRequest) Reset()         { *m = CommentRequest{} }
func (m *CommentRequest) String() string { return proto.CompactTextString(m) }
func (*CommentRequest) ProtoMessage()    {}
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *CommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentRequest.Unmarshal(m, b)
}
func (m *CommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentRequest.Marshal(b, m, deterministic)
}
func (m *CommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentRequest.Merge(m, src)
}
func (m *CommentRequest) XXX_Size() int {
	return xxx_messageInfo_CommentRequest.Size(m)
}
func (m *CommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommentRequest proto.InternalMessageInfo

func (m *CommentRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *CommentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommentRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CommentRequest) GetPostid() uint32 {
	if m != nil {
		return m.Postid
	}
	return 0
}

type CommentResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentResponse) Reset()         { *m = CommentResponse{} }
func (m *CommentResponse) String() string { return proto.CompactTextString(m) }
func (*CommentResponse) ProtoMessage()    {}
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *CommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentResponse.Unmarshal(m, b)
}
func (m *CommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentResponse.Marshal(b, m, deterministic)
}
func (m *CommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentResponse.Merge(m, src)
}
func (m *CommentResponse) XXX_Size() int {
	return xxx_messageInfo_CommentResponse.Size(m)
}
func (m *CommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommentResponse proto.InternalMessageInfo

func (m *CommentResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type FriendRequest struct {
	FriendMail           string   `protobuf:"bytes,1,opt,name=friendMail,proto3" json:"friendMail,omitempty"`
	FriendImage          string   `protobuf:"bytes,2,opt,name=friendImage,proto3" json:"friendImage,omitempty"`
	FriendName           string   `protobuf:"bytes,3,opt,name=friendName,proto3" json:"friendName,omitempty"`
	Mymail               string   `protobuf:"bytes,4,opt,name=mymail,proto3" json:"mymail,omitempty"`
	MyimageUrl           string   `protobuf:"bytes,5,opt,name=myimageUrl,proto3" json:"myimageUrl,omitempty"`
	Myusername           string   `protobuf:"bytes,6,opt,name=myusername,proto3" json:"myusername,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendRequest) Reset()         { *m = FriendRequest{} }
func (m *FriendRequest) String() string { return proto.CompactTextString(m) }
func (*FriendRequest) ProtoMessage()    {}
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *FriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRequest.Unmarshal(m, b)
}
func (m *FriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRequest.Marshal(b, m, deterministic)
}
func (m *FriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRequest.Merge(m, src)
}
func (m *FriendRequest) XXX_Size() int {
	return xxx_messageInfo_FriendRequest.Size(m)
}
func (m *FriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRequest proto.InternalMessageInfo

func (m *FriendRequest) GetFriendMail() string {
	if m != nil {
		return m.FriendMail
	}
	return ""
}

func (m *FriendRequest) GetFriendImage() string {
	if m != nil {
		return m.FriendImage
	}
	return ""
}

func (m *FriendRequest) GetFriendName() string {
	if m != nil {
		return m.FriendName
	}
	return ""
}

func (m *FriendRequest) GetMymail() string {
	if m != nil {
		return m.Mymail
	}
	return ""
}

func (m *FriendRequest) GetMyimageUrl() string {
	if m != nil {
		return m.MyimageUrl
	}
	return ""
}

func (m *FriendRequest) GetMyusername() string {
	if m != nil {
		return m.Myusername
	}
	return ""
}

func (m *FriendRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type FriendResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendResponse) Reset()         { *m = FriendResponse{} }
func (m *FriendResponse) String() string { return proto.CompactTextString(m) }
func (*FriendResponse) ProtoMessage()    {}
func (*FriendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *FriendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendResponse.Unmarshal(m, b)
}
func (m *FriendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendResponse.Marshal(b, m, deterministic)
}
func (m *FriendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendResponse.Merge(m, src)
}
func (m *FriendResponse) XXX_Size() int {
	return xxx_messageInfo_FriendResponse.Size(m)
}
func (m *FriendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FriendResponse proto.InternalMessageInfo

func (m *FriendResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GetUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserResponse) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type GetPostRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetPostResponse struct {
	Postdata             []*PostRequest `protobuf:"bytes,1,rep,name=postdata,proto3" json:"postdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetPostResponse) Reset()         { *m = GetPostResponse{} }
func (m *GetPostResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostResponse) ProtoMessage()    {}
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *GetPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostResponse.Unmarshal(m, b)
}
func (m *GetPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostResponse.Marshal(b, m, deterministic)
}
func (m *GetPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostResponse.Merge(m, src)
}
func (m *GetPostResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostResponse.Size(m)
}
func (m *GetPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostResponse proto.InternalMessageInfo

func (m *GetPostResponse) GetPostdata() []*PostRequest {
	if m != nil {
		return m.Postdata
	}
	return nil
}

type GetUserFriendRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserFriendRequest) Reset()         { *m = GetUserFriendRequest{} }
func (m *GetUserFriendRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserFriendRequest) ProtoMessage()    {}
func (*GetUserFriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *GetUserFriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserFriendRequest.Unmarshal(m, b)
}
func (m *GetUserFriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserFriendRequest.Marshal(b, m, deterministic)
}
func (m *GetUserFriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserFriendRequest.Merge(m, src)
}
func (m *GetUserFriendRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserFriendRequest.Size(m)
}
func (m *GetUserFriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserFriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserFriendRequest proto.InternalMessageInfo

func (m *GetUserFriendRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserFriendResponse struct {
	Friends              []*FriendRequest `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetUserFriendResponse) Reset()         { *m = GetUserFriendResponse{} }
func (m *GetUserFriendResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserFriendResponse) ProtoMessage()    {}
func (*GetUserFriendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{15}
}

func (m *GetUserFriendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserFriendResponse.Unmarshal(m, b)
}
func (m *GetUserFriendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserFriendResponse.Marshal(b, m, deterministic)
}
func (m *GetUserFriendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserFriendResponse.Merge(m, src)
}
func (m *GetUserFriendResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserFriendResponse.Size(m)
}
func (m *GetUserFriendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserFriendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserFriendResponse proto.InternalMessageInfo

func (m *GetUserFriendResponse) GetFriends() []*FriendRequest {
	if m != nil {
		return m.Friends
	}
	return nil
}

type People struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *People) Reset()         { *m = People{} }
func (m *People) String() string { return proto.CompactTextString(m) }
func (*People) ProtoMessage()    {}
func (*People) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{16}
}

func (m *People) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_People.Unmarshal(m, b)
}
func (m *People) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_People.Marshal(b, m, deterministic)
}
func (m *People) XXX_Merge(src proto.Message) {
	xxx_messageInfo_People.Merge(m, src)
}
func (m *People) XXX_Size() int {
	return xxx_messageInfo_People.Size(m)
}
func (m *People) XXX_DiscardUnknown() {
	xxx_messageInfo_People.DiscardUnknown(m)
}

var xxx_messageInfo_People proto.InternalMessageInfo

func (m *People) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *People) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *People) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type AllPerson struct {
	Users                []*People `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AllPerson) Reset()         { *m = AllPerson{} }
func (m *AllPerson) String() string { return proto.CompactTextString(m) }
func (*AllPerson) ProtoMessage()    {}
func (*AllPerson) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{17}
}

func (m *AllPerson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPerson.Unmarshal(m, b)
}
func (m *AllPerson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPerson.Marshal(b, m, deterministic)
}
func (m *AllPerson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPerson.Merge(m, src)
}
func (m *AllPerson) XXX_Size() int {
	return xxx_messageInfo_AllPerson.Size(m)
}
func (m *AllPerson) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPerson.DiscardUnknown(m)
}

var xxx_messageInfo_AllPerson proto.InternalMessageInfo

func (m *AllPerson) GetUsers() []*People {
	if m != nil {
		return m.Users
	}
	return nil
}

type RequestFromUsers struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFromUsers) Reset()         { *m = RequestFromUsers{} }
func (m *RequestFromUsers) String() string { return proto.CompactTextString(m) }
func (*RequestFromUsers) ProtoMessage()    {}
func (*RequestFromUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{18}
}

func (m *RequestFromUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFromUsers.Unmarshal(m, b)
}
func (m *RequestFromUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFromUsers.Marshal(b, m, deterministic)
}
func (m *RequestFromUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFromUsers.Merge(m, src)
}
func (m *RequestFromUsers) XXX_Size() int {
	return xxx_messageInfo_RequestFromUsers.Size(m)
}
func (m *RequestFromUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFromUsers.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFromUsers proto.InternalMessageInfo

func (m *RequestFromUsers) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RequestFromUserResponse struct {
	Requests             []*FriendRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RequestFromUserResponse) Reset()         { *m = RequestFromUserResponse{} }
func (m *RequestFromUserResponse) String() string { return proto.CompactTextString(m) }
func (*RequestFromUserResponse) ProtoMessage()    {}
func (*RequestFromUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{19}
}

func (m *RequestFromUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFromUserResponse.Unmarshal(m, b)
}
func (m *RequestFromUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFromUserResponse.Marshal(b, m, deterministic)
}
func (m *RequestFromUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFromUserResponse.Merge(m, src)
}
func (m *RequestFromUserResponse) XXX_Size() int {
	return xxx_messageInfo_RequestFromUserResponse.Size(m)
}
func (m *RequestFromUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFromUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFromUserResponse proto.InternalMessageInfo

func (m *RequestFromUserResponse) GetRequests() []*FriendRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

type AcceptRequest struct {
	FriendMail           string   `protobuf:"bytes,1,opt,name=friendMail,proto3" json:"friendMail,omitempty"`
	Mymail               string   `protobuf:"bytes,2,opt,name=mymail,proto3" json:"mymail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptRequest) Reset()         { *m = AcceptRequest{} }
func (m *AcceptRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptRequest) ProtoMessage()    {}
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{20}
}

func (m *AcceptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptRequest.Unmarshal(m, b)
}
func (m *AcceptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptRequest.Marshal(b, m, deterministic)
}
func (m *AcceptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptRequest.Merge(m, src)
}
func (m *AcceptRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptRequest.Size(m)
}
func (m *AcceptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptRequest proto.InternalMessageInfo

func (m *AcceptRequest) GetFriendMail() string {
	if m != nil {
		return m.FriendMail
	}
	return ""
}

func (m *AcceptRequest) GetMymail() string {
	if m != nil {
		return m.Mymail
	}
	return ""
}

type AcceptResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptResponse) Reset()         { *m = AcceptResponse{} }
func (m *AcceptResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptResponse) ProtoMessage()    {}
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{21}
}

func (m *AcceptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptResponse.Unmarshal(m, b)
}
func (m *AcceptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptResponse.Marshal(b, m, deterministic)
}
func (m *AcceptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptResponse.Merge(m, src)
}
func (m *AcceptResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptResponse.Size(m)
}
func (m *AcceptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptResponse proto.InternalMessageInfo

func (m *AcceptResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DeleteFriendRequest struct {
	FriendMail           string   `protobuf:"bytes,1,opt,name=friendMail,proto3" json:"friendMail,omitempty"`
	Mymail               string   `protobuf:"bytes,2,opt,name=mymail,proto3" json:"mymail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFriendRequest) Reset()         { *m = DeleteFriendRequest{} }
func (m *DeleteFriendRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFriendRequest) ProtoMessage()    {}
func (*DeleteFriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{22}
}

func (m *DeleteFriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFriendRequest.Unmarshal(m, b)
}
func (m *DeleteFriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFriendRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFriendRequest.Merge(m, src)
}
func (m *DeleteFriendRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFriendRequest.Size(m)
}
func (m *DeleteFriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFriendRequest proto.InternalMessageInfo

func (m *DeleteFriendRequest) GetFriendMail() string {
	if m != nil {
		return m.FriendMail
	}
	return ""
}

func (m *DeleteFriendRequest) GetMymail() string {
	if m != nil {
		return m.Mymail
	}
	return ""
}

type DeleteFriendResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFriendResponse) Reset()         { *m = DeleteFriendResponse{} }
func (m *DeleteFriendResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFriendResponse) ProtoMessage()    {}
func (*DeleteFriendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{23}
}

func (m *DeleteFriendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFriendResponse.Unmarshal(m, b)
}
func (m *DeleteFriendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFriendResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFriendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFriendResponse.Merge(m, src)
}
func (m *DeleteFriendResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFriendResponse.Size(m)
}
func (m *DeleteFriendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFriendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFriendResponse proto.InternalMessageInfo

func (m *DeleteFriendResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type SinglePostReturing struct {
	Postid               uint32            `protobuf:"varint,1,opt,name=postid,proto3" json:"postid,omitempty"`
	Description          string            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl             string            `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Email                string            `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Username             string            `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Comments             []*CommentRequest `protobuf:"bytes,6,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SinglePostReturing) Reset()         { *m = SinglePostReturing{} }
func (m *SinglePostReturing) String() string { return proto.CompactTextString(m) }
func (*SinglePostReturing) ProtoMessage()    {}
func (*SinglePostReturing) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{24}
}

func (m *SinglePostReturing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SinglePostReturing.Unmarshal(m, b)
}
func (m *SinglePostReturing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SinglePostReturing.Marshal(b, m, deterministic)
}
func (m *SinglePostReturing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SinglePostReturing.Merge(m, src)
}
func (m *SinglePostReturing) XXX_Size() int {
	return xxx_messageInfo_SinglePostReturing.Size(m)
}
func (m *SinglePostReturing) XXX_DiscardUnknown() {
	xxx_messageInfo_SinglePostReturing.DiscardUnknown(m)
}

var xxx_messageInfo_SinglePostReturing proto.InternalMessageInfo

func (m *SinglePostReturing) GetPostid() uint32 {
	if m != nil {
		return m.Postid
	}
	return 0
}

func (m *SinglePostReturing) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SinglePostReturing) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *SinglePostReturing) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SinglePostReturing) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SinglePostReturing) GetComments() []*CommentRequest {
	if m != nil {
		return m.Comments
	}
	return nil
}

type MultiPostReturing struct {
	Posts                []*SinglePostReturing `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MultiPostReturing) Reset()         { *m = MultiPostReturing{} }
func (m *MultiPostReturing) String() string { return proto.CompactTextString(m) }
func (*MultiPostReturing) ProtoMessage()    {}
func (*MultiPostReturing) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{25}
}

func (m *MultiPostReturing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiPostReturing.Unmarshal(m, b)
}
func (m *MultiPostReturing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiPostReturing.Marshal(b, m, deterministic)
}
func (m *MultiPostReturing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiPostReturing.Merge(m, src)
}
func (m *MultiPostReturing) XXX_Size() int {
	return xxx_messageInfo_MultiPostReturing.Size(m)
}
func (m *MultiPostReturing) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiPostReturing.DiscardUnknown(m)
}

var xxx_messageInfo_MultiPostReturing proto.InternalMessageInfo

func (m *MultiPostReturing) GetPosts() []*SinglePostReturing {
	if m != nil {
		return m.Posts
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{26}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterUserRequest)(nil), "proto.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "proto.RegisterUserResponse")
	proto.RegisterType((*LoginUserRequest)(nil), "proto.LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "proto.LoginUserResponse")
	proto.RegisterType((*PostRequest)(nil), "proto.PostRequest")
	proto.RegisterType((*PostResponse)(nil), "proto.PostResponse")
	proto.RegisterType((*CommentRequest)(nil), "proto.CommentRequest")
	proto.RegisterType((*CommentResponse)(nil), "proto.CommentResponse")
	proto.RegisterType((*FriendRequest)(nil), "proto.FriendRequest")
	proto.RegisterType((*FriendResponse)(nil), "proto.FriendResponse")
	proto.RegisterType((*GetUserRequest)(nil), "proto.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "proto.GetUserResponse")
	proto.RegisterType((*GetPostRequest)(nil), "proto.GetPostRequest")
	proto.RegisterType((*GetPostResponse)(nil), "proto.GetPostResponse")
	proto.RegisterType((*GetUserFriendRequest)(nil), "proto.GetUserFriendRequest")
	proto.RegisterType((*GetUserFriendResponse)(nil), "proto.GetUserFriendResponse")
	proto.RegisterType((*People)(nil), "proto.People")
	proto.RegisterType((*AllPerson)(nil), "proto.AllPerson")
	proto.RegisterType((*RequestFromUsers)(nil), "proto.RequestFromUsers")
	proto.RegisterType((*RequestFromUserResponse)(nil), "proto.RequestFromUserResponse")
	proto.RegisterType((*AcceptRequest)(nil), "proto.AcceptRequest")
	proto.RegisterType((*AcceptResponse)(nil), "proto.AcceptResponse")
	proto.RegisterType((*DeleteFriendRequest)(nil), "proto.DeleteFriendRequest")
	proto.RegisterType((*DeleteFriendResponse)(nil), "proto.DeleteFriendResponse")
	proto.RegisterType((*SinglePostReturing)(nil), "proto.SinglePostReturing")
	proto.RegisterType((*MultiPostReturing)(nil), "proto.MultiPostReturing")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 932 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0x9d, 0xda, 0xc9, 0x9e, 0xd6, 0x6d, 0x77, 0x9a, 0x66, 0x8d, 0x17, 0xad, 0xaa, 0x41,
	0x5a, 0x15, 0x09, 0xc2, 0xb2, 0x7b, 0x81, 0x04, 0x08, 0x11, 0xd1, 0xdd, 0x6a, 0xc5, 0x06, 0x55,
	0x5e, 0x95, 0x5b, 0x64, 0xe2, 0x21, 0xb2, 0xea, 0x3f, 0x3c, 0x13, 0x50, 0xaf, 0x78, 0x0a, 0xae,
	0x79, 0x24, 0xae, 0xb9, 0xe4, 0x4d, 0xd0, 0xfc, 0x78, 0x3a, 0xe3, 0x38, 0x0d, 0xa0, 0xbd, 0x8a,
	0xce, 0xff, 0xf9, 0xce, 0x39, 0xf3, 0xc5, 0x10, 0x50, 0xd2, 0xfc, 0x92, 0x2d, 0xc9, 0xac, 0x6e,
	0x2a, 0x56, 0x21, 0x4f, 0xfc, 0xe0, 0xdf, 0xe0, 0x24, 0x26, 0xab, 0x8c, 0x32, 0xd2, 0x5c, 0x53,
	0xd2, 0xc4, 0xe4, 0xe7, 0x35, 0xa1, 0x0c, 0x45, 0x30, 0x5e, 0x53, 0xd2, 0x94, 0x49, 0x41, 0x42,
	0xe7, 0xcc, 0x39, 0x7f, 0x10, 0x6b, 0x19, 0x4d, 0xc0, 0x23, 0x45, 0x92, 0xe5, 0xa1, 0x2b, 0x0c,
	0x52, 0xe0, 0x11, 0x75, 0x42, 0xe9, 0xaf, 0x55, 0x93, 0x86, 0x43, 0x19, 0xd1, 0xca, 0xdc, 0x96,
	0x15, 0xc9, 0x8a, 0x5c, 0x37, 0x79, 0xb8, 0x27, 0x6d, 0xad, 0x8c, 0x67, 0x30, 0xb1, 0x1b, 0xa0,
	0x75, 0x55, 0x52, 0x82, 0xa6, 0xe0, 0x37, 0x84, 0xae, 0x73, 0xa6, 0xea, 0x2b, 0x09, 0x5f, 0xc0,
	0xf1, 0x9b, 0x6a, 0x95, 0x95, 0x66, 0xb7, 0xba, 0x23, 0x67, 0x5b, 0x47, 0xae, 0xdd, 0x11, 0xfe,
	0xc3, 0x81, 0x87, 0x46, 0x1a, 0x55, 0xf3, 0x10, 0xdc, 0x2c, 0x15, 0x49, 0x86, 0xb1, 0x9b, 0xa5,
	0xd6, 0x14, 0xdc, 0x6d, 0x53, 0x18, 0x76, 0x6a, 0x6e, 0x43, 0xca, 0x23, 0x58, 0x75, 0x43, 0xca,
	0xd0, 0x93, 0x11, 0x42, 0x30, 0x70, 0xfa, 0x16, 0xce, 0xdf, 0x1d, 0xd8, 0xbf, 0xaa, 0x28, 0x6b,
	0x31, 0x9e, 0xc1, 0x7e, 0x4a, 0xe8, 0xb2, 0xc9, 0x6a, 0x96, 0x55, 0xa5, 0x42, 0x6a, 0xaa, 0xac,
	0xda, 0xee, 0x66, 0xed, 0x9e, 0x6e, 0xa7, 0xe0, 0x57, 0x32, 0x9d, 0xec, 0x55, 0x49, 0x16, 0x6e,
	0xcf, 0xc6, 0x8d, 0x9f, 0xc2, 0x81, 0x6c, 0x6b, 0xc7, 0x9e, 0x72, 0x38, 0xfc, 0xa6, 0x2a, 0x0a,
	0x52, 0x6a, 0x04, 0x21, 0x8c, 0x96, 0x52, 0xa3, 0x5c, 0x5b, 0x11, 0x21, 0xd8, 0x33, 0x66, 0xbc,
	0x77, 0xcf, 0x7c, 0xa7, 0xe0, 0xd7, 0x15, 0x65, 0x59, 0x2a, 0x3a, 0x0e, 0x62, 0x25, 0xe1, 0x0f,
	0xe1, 0x48, 0x57, 0xdb, 0xd1, 0xd8, 0xdf, 0x0e, 0x04, 0xaf, 0x9a, 0x8c, 0x94, 0x69, 0xdb, 0xd8,
	0x13, 0x80, 0x9f, 0x84, 0x62, 0x71, 0x77, 0x43, 0x86, 0x86, 0x8f, 0x5e, 0x4a, 0xaf, 0xf9, 0x38,
	0x55, 0x97, 0xa6, 0xea, 0x2e, 0xc3, 0x77, 0x1c, 0xc6, 0xd0, 0xcc, 0xc0, 0x35, 0xbc, 0x97, 0xe2,
	0x56, 0xa0, 0x51, 0x83, 0x96, 0x12, 0x8f, 0x2b, 0x6e, 0xf5, 0xd2, 0xe4, 0xa8, 0x0d, 0x8d, 0xb4,
	0xeb, 0x55, 0xf8, 0xad, 0x5d, 0x1f, 0xe1, 0x14, 0x7c, 0xca, 0x12, 0xb6, 0xa6, 0xe1, 0x48, 0xe6,
	0x95, 0x12, 0x3e, 0x87, 0xc3, 0x16, 0xe2, 0x8e, 0x69, 0x3c, 0x85, 0xc3, 0x4b, 0xc2, 0x76, 0x3e,
	0x26, 0xfc, 0x03, 0x1c, 0x69, 0x3f, 0x95, 0xf2, 0x7f, 0x71, 0x84, 0x06, 0x3b, 0xec, 0xf0, 0x80,
	0x6c, 0xc4, 0xbc, 0xf8, 0xfe, 0x46, 0xe6, 0xa2, 0x11, 0xeb, 0x04, 0x67, 0x30, 0xe6, 0x67, 0x90,
	0x26, 0x2c, 0x09, 0x9d, 0xb3, 0xe1, 0xf9, 0xfe, 0x73, 0x24, 0x49, 0x6e, 0x66, 0xa4, 0x8b, 0xb5,
	0x0f, 0xfe, 0x08, 0x26, 0x0a, 0x8b, 0x7d, 0x07, 0xfd, 0x05, 0x2f, 0xe1, 0xb4, 0xe3, 0xad, 0xcb,
	0x8e, 0xe4, 0x8a, 0xa9, 0xaa, 0x3a, 0x51, 0x55, 0xad, 0xac, 0x71, 0xeb, 0x84, 0xbf, 0x07, 0xff,
	0x8a, 0x54, 0x75, 0xfe, 0xae, 0x27, 0xf7, 0x0c, 0x1e, 0xcc, 0xf3, 0xfc, 0x8a, 0x34, 0xb4, 0x2a,
	0xd1, 0x07, 0xe0, 0xf1, 0x54, 0x6d, 0x4b, 0x41, 0x3b, 0x08, 0x51, 0x38, 0x96, 0x36, 0x7c, 0x0e,
	0xc7, 0xaa, 0xbb, 0x57, 0x4d, 0x55, 0x70, 0x68, 0x74, 0x0b, 0xf8, 0x6f, 0xe1, 0x51, 0xc7, 0x53,
	0xc3, 0x7f, 0x06, 0xe3, 0x46, 0x9a, 0xee, 0xc7, 0xaf, 0xbd, 0xf0, 0x25, 0x04, 0xf3, 0xe5, 0x92,
	0xd4, 0xec, 0xdf, 0x3e, 0xbc, 0xbb, 0x67, 0xe3, 0x9a, 0xcf, 0x86, 0x9f, 0x77, 0x9b, 0x68, 0xc7,
	0x79, 0x2f, 0xe0, 0xe4, 0x82, 0xe4, 0x84, 0x91, 0xff, 0xf6, 0xe2, 0xb7, 0x15, 0x9e, 0xc1, 0xc4,
	0x4e, 0xb7, 0xa3, 0xfc, 0x9f, 0x0e, 0xa0, 0xb7, 0x59, 0xb9, 0xca, 0x89, 0xbc, 0x44, 0xb6, 0x6e,
	0xb2, 0x72, 0x65, 0xb0, 0x98, 0x63, 0xb2, 0x58, 0x97, 0xe3, 0xdd, 0xfb, 0x39, 0x7e, 0xb8, 0x8d,
	0xe3, 0xf7, 0x3a, 0x97, 0xb3, 0x8d, 0xcb, 0xd1, 0xa7, 0x30, 0x56, 0x14, 0x4c, 0x43, 0x5f, 0xac,
	0xf0, 0x54, 0xad, 0xd0, 0xa6, 0xee, 0x58, 0xbb, 0xe1, 0x0b, 0x78, 0xb8, 0x58, 0xe7, 0x2c, 0xb3,
	0xf0, 0x7c, 0x02, 0x1e, 0x47, 0xd0, 0xde, 0xc1, 0x7b, 0x2a, 0xc9, 0x26, 0xf2, 0x58, 0xfa, 0xe1,
	0x11, 0x78, 0x2f, 0x8b, 0x9a, 0xdd, 0x3e, 0xff, 0xcb, 0x87, 0x60, 0x9e, 0xa6, 0xf3, 0xba, 0x7e,
	0x2b, 0xbf, 0x4e, 0xd0, 0x4b, 0x18, 0xb7, 0xdf, 0x03, 0x28, 0x52, 0x89, 0x7a, 0xbe, 0x50, 0xa2,
	0xc7, 0xbd, 0x36, 0xb9, 0x0f, 0x3c, 0x40, 0x5f, 0x82, 0x27, 0xfe, 0xdf, 0xd1, 0x23, 0xe5, 0xd7,
	0xfd, 0x68, 0x88, 0xc2, 0x4d, 0x83, 0x8e, 0xfe, 0x0c, 0xe0, 0xba, 0xce, 0xab, 0x24, 0xe5, 0xcd,
	0xa3, 0x1e, 0x36, 0x89, 0x4e, 0x2c, 0x9d, 0x0e, 0xfc, 0x1a, 0x02, 0x19, 0xa8, 0x06, 0x88, 0xfa,
	0x07, 0x1a, 0x4d, 0xbb, 0x6a, 0x9d, 0xe1, 0x0b, 0x80, 0x45, 0x72, 0xa3, 0x0e, 0x0c, 0xf5, 0x3e,
	0xa9, 0xe8, 0xb4, 0xa3, 0xd5, 0xc1, 0x9f, 0xc3, 0x48, 0x71, 0x95, 0x2e, 0x6c, 0xb3, 0xbb, 0x2e,
	0xdc, 0x21, 0x73, 0x3c, 0x40, 0x5f, 0xc1, 0xbe, 0x52, 0x0a, 0xd0, 0x46, 0xbc, 0x89, 0x7b, 0xda,
	0x55, 0xeb, 0xf8, 0x37, 0x10, 0x58, 0x3c, 0x89, 0x1e, 0xdb, 0xa5, 0x6c, 0x08, 0xef, 0xf7, 0x1b,
	0x75, 0xb6, 0x8f, 0x15, 0xa9, 0x09, 0xbe, 0x3c, 0x50, 0xce, 0xe2, 0x66, 0xa2, 0x63, 0x25, 0x69,
	0xd2, 0x13, 0xc5, 0x8f, 0x3a, 0x3c, 0xa5, 0x17, 0xdf, 0x65, 0xba, 0xe8, 0x49, 0xbf, 0xc1, 0x28,
	0x7e, 0x01, 0x27, 0x92, 0x5f, 0x3a, 0xff, 0x0f, 0x6d, 0x61, 0x93, 0xc4, 0xf4, 0x32, 0x6c, 0x46,
	0xc2, 0x03, 0xf4, 0x1a, 0x0e, 0x4c, 0xb2, 0xd0, 0xd7, 0xdc, 0x43, 0x48, 0xfa, 0x9a, 0xfb, 0xd8,
	0x05, 0x0f, 0xd0, 0x0b, 0x18, 0x71, 0xb4, 0x7c, 0x2f, 0xf6, 0x2c, 0xda, 0x23, 0xde, 0x78, 0x93,
	0x78, 0xf0, 0xa3, 0x2f, 0x4c, 0x2f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x04, 0x78, 0xae,
	0xf9, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddAppServiceClient is the client API for AddAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddAppServiceClient interface {
	Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	Login(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	UploadPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	UploadComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	MakeFriend(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
	GetUserFriend(ctx context.Context, in *GetUserFriendRequest, opts ...grpc.CallOption) (*GetUserFriendResponse, error)
	AllPeople(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllPerson, error)
	RequestFromUser(ctx context.Context, in *RequestFromUsers, opts ...grpc.CallOption) (*RequestFromUserResponse, error)
	AcceptFriendRequest(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error)
	DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error)
	AllPost(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MultiPostReturing, error)
}

type addAppServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddAppServiceClient(cc *grpc.ClientConn) AddAppServiceClient {
	return &addAppServiceClient{cc}
}

func (c *addAppServiceClient) Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) Login(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) UploadPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/UploadPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) UploadComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/UploadComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) MakeFriend(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendResponse, error) {
	out := new(FriendResponse)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/MakeFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) GetUserPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/GetUserPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) GetUserFriend(ctx context.Context, in *GetUserFriendRequest, opts ...grpc.CallOption) (*GetUserFriendResponse, error) {
	out := new(GetUserFriendResponse)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/GetUserFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) AllPeople(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllPerson, error) {
	out := new(AllPerson)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/AllPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) RequestFromUser(ctx context.Context, in *RequestFromUsers, opts ...grpc.CallOption) (*RequestFromUserResponse, error) {
	out := new(RequestFromUserResponse)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/RequestFromUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) AcceptFriendRequest(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error) {
	out := new(AcceptResponse)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/AcceptFriendRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error) {
	out := new(DeleteFriendResponse)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/DeleteFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addAppServiceClient) AllPost(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MultiPostReturing, error) {
	out := new(MultiPostReturing)
	err := c.cc.Invoke(ctx, "/proto.AddAppService/AllPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddAppServiceServer is the server API for AddAppService service.
type AddAppServiceServer interface {
	Register(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	Login(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	UploadPost(context.Context, *PostRequest) (*PostResponse, error)
	UploadComment(context.Context, *CommentRequest) (*CommentResponse, error)
	MakeFriend(context.Context, *FriendRequest) (*FriendResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUserPost(context.Context, *GetPostRequest) (*GetPostResponse, error)
	GetUserFriend(context.Context, *GetUserFriendRequest) (*GetUserFriendResponse, error)
	AllPeople(context.Context, *Empty) (*AllPerson, error)
	RequestFromUser(context.Context, *RequestFromUsers) (*RequestFromUserResponse, error)
	AcceptFriendRequest(context.Context, *AcceptRequest) (*AcceptResponse, error)
	DeleteFriend(context.Context, *DeleteFriendRequest) (*DeleteFriendResponse, error)
	AllPost(context.Context, *Empty) (*MultiPostReturing, error)
}

// UnimplementedAddAppServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddAppServiceServer struct {
}

func (*UnimplementedAddAppServiceServer) Register(ctx context.Context, req *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedAddAppServiceServer) Login(ctx context.Context, req *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAddAppServiceServer) UploadPost(ctx context.Context, req *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadPost not implemented")
}
func (*UnimplementedAddAppServiceServer) UploadComment(ctx context.Context, req *CommentRequest) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadComment not implemented")
}
func (*UnimplementedAddAppServiceServer) MakeFriend(ctx context.Context, req *FriendRequest) (*FriendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeFriend not implemented")
}
func (*UnimplementedAddAppServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedAddAppServiceServer) GetUserPost(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPost not implemented")
}
func (*UnimplementedAddAppServiceServer) GetUserFriend(ctx context.Context, req *GetUserFriendRequest) (*GetUserFriendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFriend not implemented")
}
func (*UnimplementedAddAppServiceServer) AllPeople(ctx context.Context, req *Empty) (*AllPerson, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllPeople not implemented")
}
func (*UnimplementedAddAppServiceServer) RequestFromUser(ctx context.Context, req *RequestFromUsers) (*RequestFromUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestFromUser not implemented")
}
func (*UnimplementedAddAppServiceServer) AcceptFriendRequest(ctx context.Context, req *AcceptRequest) (*AcceptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptFriendRequest not implemented")
}
func (*UnimplementedAddAppServiceServer) DeleteFriend(ctx context.Context, req *DeleteFriendRequest) (*DeleteFriendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFriend not implemented")
}
func (*UnimplementedAddAppServiceServer) AllPost(ctx context.Context, req *Empty) (*MultiPostReturing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllPost not implemented")
}

func RegisterAddAppServiceServer(s *grpc.Server, srv AddAppServiceServer) {
	s.RegisterService(&_AddAppService_serviceDesc, srv)
}

func _AddAppService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).Register(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).Login(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_UploadPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).UploadPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/UploadPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).UploadPost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_UploadComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).UploadComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/UploadComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).UploadComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_MakeFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).MakeFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/MakeFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).MakeFriend(ctx, req.(*FriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_GetUserPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).GetUserPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/GetUserPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).GetUserPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_GetUserFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).GetUserFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/GetUserFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).GetUserFriend(ctx, req.(*GetUserFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_AllPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).AllPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/AllPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).AllPeople(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_RequestFromUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFromUsers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).RequestFromUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/RequestFromUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).RequestFromUser(ctx, req.(*RequestFromUsers))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_AcceptFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).AcceptFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/AcceptFriendRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).AcceptFriendRequest(ctx, req.(*AcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_DeleteFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).DeleteFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/DeleteFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).DeleteFriend(ctx, req.(*DeleteFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddAppService_AllPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddAppServiceServer).AllPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddAppService/AllPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddAppServiceServer).AllPost(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddAppService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddAppService",
	HandlerType: (*AddAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AddAppService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AddAppService_Login_Handler,
		},
		{
			MethodName: "UploadPost",
			Handler:    _AddAppService_UploadPost_Handler,
		},
		{
			MethodName: "UploadComment",
			Handler:    _AddAppService_UploadComment_Handler,
		},
		{
			MethodName: "MakeFriend",
			Handler:    _AddAppService_MakeFriend_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AddAppService_GetUser_Handler,
		},
		{
			MethodName: "GetUserPost",
			Handler:    _AddAppService_GetUserPost_Handler,
		},
		{
			MethodName: "GetUserFriend",
			Handler:    _AddAppService_GetUserFriend_Handler,
		},
		{
			MethodName: "AllPeople",
			Handler:    _AddAppService_AllPeople_Handler,
		},
		{
			MethodName: "RequestFromUser",
			Handler:    _AddAppService_RequestFromUser_Handler,
		},
		{
			MethodName: "AcceptFriendRequest",
			Handler:    _AddAppService_AcceptFriendRequest_Handler,
		},
		{
			MethodName: "DeleteFriend",
			Handler:    _AddAppService_DeleteFriend_Handler,
		},
		{
			MethodName: "AllPost",
			Handler:    _AddAppService_AllPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
